language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
services:
- docker
sudo: required
install:
- make bootstrap
script:
- make build test dist
deploy:
  provider: gcs
  access_key_id:
    secure: "e/p8ZPR3CxtVmhQgq1hP3iFw1/s0/Z4BC/Usdj2HBhRG4gnDjCYDL25JGd6hUq+CEwBYQU5zZjkjCYvzZyjhYA3sZPp7IbfGGm1/2Xx51qgs9kcEgiisFvS2mjC1l0qmoL8SCk9L2gJVYNwkuy35sD5+XQyuEWjk82qCqnx1mOOQXLzeKnFgHEy8xWnuslnAPY6SYOTYnu+ngAPb8GV9CJXgV12jv+gdyV5pkFXRWwMhq2aGohoKOP1aHGe4mF1Yvrt8qog0za2lfA8aakpYfuiVq3z6G8+WgG3GjsPzGTQVnv9mverQOHXnrvTsbP9gX0VSWXtVOsgpcNZxqjsdg1vro1HGD2Q7F5MocJAkSTSVAFk598XmBzkI445PQCBciejDy/yxLWojiXuTYbzLi1VDJkfRT61mxVnFIfYpDXD+YujWMAQQG1h0hNDe096vc3HqG0HJUUhwjVMHIVa8cjcDZ5zok5ZwrKXYTxxsSDwrdniFtDO7qVISC7NJ6Q13U2S3sNmonZL9CJkdQijrDdtDag46n/pbvAZWmCJdqR3Sjjwu1hrGpN3Dakgm8aihOcMFIAjuHzQZzJXIoTIXPjWOedvtGvwjpTEz6zq4+1vd9sjXe5CqUcYh2l8NQP6Zb3SL44Qu4ZHwr2LwiQP4T7pns100QCOFe83MGWQ5WX0="
  secret_access_key:
    secure: "Z6GzxuV17FjY4s0W7SlfWQVutcj34/DNpsa3rVJn3UDKIKbSr0YxWGeISeYP4acGIueNujd30f/3/tmYLGCmswk0m4zEwaHIXZHG0MFR8LuOUjTeo6eVuPr9mMB2GrORrLifnfbi5lkpcXVEGdY9X6YTLkQLG+stsL0epoJ7HoHdMqNeNvasgpa2ZNmFBfm7qHVd69Ta2W09/wMKdo76n4qub7BBFKno9IUs1+LfsaTbE4QOsKYv4K3nUfDmHJLNMWrPW9yHFo8jTHsHnicpVzQQKvcCcPFREQljO+a4hUKEy3O6TihbfKXJ2zZBkiiylNnSbvMgp5WAzJsbddkjKz3Wi7ymAS3pWwRzdE9uVqKzbnbL4i8xSXceC1M4HPohQ/0akF75627I4N7rcqYJT+x55Eb+vGPFVBh7YYvIn58b2lFJdVXs5EYaS6SaNoi5ElWZrBpYER/wXuKSSeKhUUeJSckU+DXaJWIGzmvooAxzthPZg/ODg9OKlCDDr7minLQ06It1msKCwDHqQ1ioEMFJx7iOGyw80al0EI92T8bRG/erVCGOfzJjq9k6rRJPl3IOJRqAyX3X8PmVlZ9HeFx8U9Bm6Vtz2fEqrwQT1tchbZW8XJjygujIQbQOdBHozBbmmssn3lkIizWZ3jhYi8DUpnEPVBedePHlvKcUFI0="
  bucket: workflow-cli
  local-dir: _dist
  on:
    branch: master
  acl: public-read
